# Build stage
FROM node:20-alpine AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

# Railway passes service variables as build args
# Vite needs them as env vars during build
ARG VITE_ARCGIS_API_KEY
ARG VITE_AUTH0_CLIENT_ID
ARG VITE_AUTH0_DOMAIN
ARG VITE_AUTH0_LOGOUT_URI
ARG VITE_AUTH0_REDIRECT_URI
ARG VITE_AUTH0_VFR3D_API_AUDIENCE
ARG VITE_CESIUM_API_KEY
ARG VITE_EMAILJS_CONTACT_FORM_TEMPLATE_ID
ARG VITE_EMAILJS_USER_ID
ARG VITE_EMAILJS_VFR3D_EMAIL_SERVICE_ID
ARG VITE_FAA_ARCGIS_BASE_URL
ARG VITE_VFR3D_BASE_URL
ARG VITE_PREFLIGHT_API_BASE_URL
ARG VITE_PREFLIGHT_API_KEY

ENV VITE_ARCGIS_API_KEY=$VITE_ARCGIS_API_KEY
ENV VITE_AUTH0_CLIENT_ID=$VITE_AUTH0_CLIENT_ID
ENV VITE_AUTH0_DOMAIN=$VITE_AUTH0_DOMAIN
ENV VITE_AUTH0_LOGOUT_URI=$VITE_AUTH0_LOGOUT_URI
ENV VITE_AUTH0_REDIRECT_URI=$VITE_AUTH0_REDIRECT_URI
ENV VITE_AUTH0_VFR3D_API_AUDIENCE=$VITE_AUTH0_VFR3D_API_AUDIENCE
ENV VITE_CESIUM_API_KEY=$VITE_CESIUM_API_KEY
ENV VITE_EMAILJS_CONTACT_FORM_TEMPLATE_ID=$VITE_EMAILJS_CONTACT_FORM_TEMPLATE_ID
ENV VITE_EMAILJS_USER_ID=$VITE_EMAILJS_USER_ID
ENV VITE_EMAILJS_VFR3D_EMAIL_SERVICE_ID=$VITE_EMAILJS_VFR3D_EMAIL_SERVICE_ID
ENV VITE_FAA_ARCGIS_BASE_URL=$VITE_FAA_ARCGIS_BASE_URL
ENV VITE_VFR3D_BASE_URL=$VITE_VFR3D_BASE_URL
ENV VITE_PREFLIGHT_API_BASE_URL=$VITE_PREFLIGHT_API_BASE_URL
ENV VITE_PREFLIGHT_API_KEY=$VITE_PREFLIGHT_API_KEY

# Generate TanStack Router route tree (gitignored, must be created before tsc)
RUN npx @tanstack/router-cli generate
RUN npm run build

# Serve stage - nginx:alpine auto-templates files in /etc/nginx/templates/
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/templates/default.conf.template

EXPOSE 80
